--
-- PostgreSQL database dump
--

\restrict nZlIMzBEVaRwLf6KVnYdf45kEkbZ4rGb6LDdQ3p1KyxfXREZCJmtaJH30Ug3XGm

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-26 02:34:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 24610)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id bigint NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24609)
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16402)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16401)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24593)
-- Name: plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plan (
    id bigint NOT NULL,
    billing_cycle character varying(255),
    name character varying(255),
    price double precision NOT NULL
);


ALTER TABLE public.plan OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24592)
-- Name: plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24603)
-- Name: subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription (
    id bigint NOT NULL,
    customer_id bigint,
    end_date date,
    plan_id bigint,
    start_date date,
    status character varying(255)
);


ALTER TABLE public.subscription OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24602)
-- Name: subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5033 (class 0 OID 24610)
-- Dependencies: 226
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin (id, password, username) FROM stdin;
1	Yam@123	yamini
\.


--
-- TOC entry 5027 (class 0 OID 16402)
-- Dependencies: 220
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer (id, email, name) FROM stdin;
2	srisha@gmail.com	Srisha
4	khyathi@gmail.com	khyathi
1	yaminii@gmail.com	Yamini
5	priyanka@gmail.com	priyanka
6	vero@gmail.com	Veronica
7	jahnvi@gmail.com	Jahnvi
8	aditya@gmail.com	Aditya
9	ayaan@gmail.com	ayaan
10	jai@gmail.com	jai
11	har@gmail.com	harsha
\.


--
-- TOC entry 5029 (class 0 OID 24593)
-- Dependencies: 222
-- Data for Name: plan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plan (id, billing_cycle, name, price) FROM stdin;
3	Monthly	Enterprise	1999
2	Monthly	Pro	799
1	1 Month	Basic	299
\.


--
-- TOC entry 5031 (class 0 OID 24603)
-- Dependencies: 224
-- Data for Name: subscription; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscription (id, customer_id, end_date, plan_id, start_date, status) FROM stdin;
8	5	2026-09-25	2	2026-03-25	\N
5	1	2027-09-23	3	2026-09-23	\N
9	6	2026-10-28	1	2026-09-28	ACTIVE
11	8	2026-10-24	1	2026-09-23	ACTIVE
6	2	2026-09-17	1	2026-08-17	\N
7	4	2026-10-24	1	2026-09-23	ACTIVE
12	9	2026-07-08	2	2026-01-08	EXPIRED
10	7	2027-03-27	2	2026-09-24	ACTIVE
13	10	2027-03-24	2	2026-09-24	ACTIVE
\.


--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 225
-- Name: admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_id_seq', 2, true);


--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 219
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 11, true);


--
-- TOC entry 5041 (class 0 OID 0)
-- Dependencies: 221
-- Name: plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plan_id_seq', 5, true);


--
-- TOC entry 5042 (class 0 OID 0)
-- Dependencies: 223
-- Name: subscription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_id_seq', 13, true);


--
-- TOC entry 4878 (class 2606 OID 24617)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 16409)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 24601)
-- Name: plan plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan
    ADD CONSTRAINT plan_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 24608)
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (id);


-- Completed on 2026-09-26 02:34:16

--
-- PostgreSQL database dump complete
--

\unrestrict nZlIMzBEVaRwLf6KVnYdf45kEkbZ4rGb6LDdQ3p1KyxfXREZCJmtaJH30Ug3XGm

